using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using TheCanalaveLibrary.Core;

namespace TheCanalaveLibrary.Server;

public class DataSeeder
{
    private readonly ApplicationDbContext _context;
    private readonly UserManager<User> _userManager;
    private readonly RoleManager<ApplicationRole> _roleManager;

    public DataSeeder(ApplicationDbContext context, UserManager<User> userManager, RoleManager<ApplicationRole> roleManager)
    {
        _context = context;
        _userManager = userManager;
        _roleManager = roleManager;
    }

    public async Task SeedDevelopmentDataAsync()
    {
        // 1. Ensure the database is created and migrations are applied
        await _context.Database.MigrateAsync();

        // 2. Check if data already exists. If so, do nothing.
        // We check for Users, but you could also check for Stories.
        if (await _context.Users.AnyAsync(u => u.UserName == "TestUser"))
        {
            return; // Test data already seeded
        }

        // 3. Create Test Users
        var testUser = new User
        {
            UserName = "TestUser",
            Email = "test@example.com",
            EmailConfirmed = true,
            ShowMatureContent = true,
            ThemeId = 1,
            Tagline = "I am a Test User!",
        };
        await _userManager.CreateAsync(testUser, "Password123!");

        var adminUser = new User
        {
            UserName = "AdminUser",
            Email = "admin@example.com",
            EmailConfirmed = true,
            ShowMatureContent = true,
            ThemeId = 1,
            Tagline = "I am the admin!",
        };
        await _userManager.CreateAsync(adminUser, "Password123!");
        
        // 4. Assign Roles
        // (This assumes you've seeded "Admin" in OnModelCreating)
        await _userManager.AddToRoleAsync(adminUser, "Admin");

        // 5. Create Test Stories
        var testStory = new Story
        {
            Author = testUser, // Link to the user
            Rating = Rating.M,
            StoryStatusId = StoryStatusEnum.InProgress,
            WordCount = 12000,
            ViewCount = 150,
            PublishedDate = DateTime.UtcNow.AddDays(-10),
            LastUpdatedDate = DateTime.UtcNow.AddDays(-1),
            
            // ... etc. ...
        };
        
        // 6. Create Partitions for the Story
        testStory.StoryListing = new StoryListing
        {
            StoryTitle = "My First Test Story",
            ShortDescription = "A short description for the test story."
            // The SearchVector will be generated by the database
        };

        testStory.StoryDetail = new StoryDetail
        {
            LongDescription = "This is the full, long description...",
            Slug = "my-first-test-story",
            PostApprovalStatus = StoryStatusEnum.InProgress
        };

        _context.Stories.Add(testStory);
        /*
        // 7. Create Test Comments
        var testComment = new ChapterComment
        {
            // Note: Can't link to a Chapter yet, as we haven't saved 'testStory'
            // We'd have to call SaveChanges() first, then add chapters, then comments.
            Author = testUser,
            CommentText = "This is a test comment!",
            DatePosted = DateTime.UtcNow,
            ChapterId = 1 // This is simplified; you'd add a Chapter first
        };*/
        
        // For a real seeder, you'd create a story, save changes to get its ID,
        // then create chapters, save changes, then create comments.
        // For this example, we'll just save the story.
        
        await _context.SaveChangesAsync();
    }
}