using FluentAssertions;
using Microsoft.Extensions.DependencyInjection;
using TheCanalaveLibrary.Core;
using TheCanalaveLibrary.Server;

namespace TheCanalaveLibrary.Tests.Integration;

/// <summary>
/// Integration test for the bulk-import commit path (Feature 63, WU38d): parsed drafts →
/// <c>CreateChapterAsync</c> loop (what <c>StoryChapterImport</c> does on commit) → unpublished
/// chapters with server-assigned numbers and real word counts. Uses a real EPUB generated by the
/// WU38c writer — the whole export→import→commit chain against a real Postgres.
/// Tier: Integration.
/// </summary>
[Collection("Postgres")]
public class ImportCommitTests(PostgresFixture postgres) : IntegrationTestBase(postgres)
{
    [Fact]
    public async Task EpubDrafts_CommitAsUnpublishedChapters_InOrder_WithWordCounts()
    {
        int authorId = await SeedUserAsync();
        SetActiveUser(authorId);
        int storyId = await SeedStoryAsync(authorId);

        // A real EPUB from the WU38c writer (round-trip fixture strategy — no binary test assets).
        byte[] epub = EpubWriter.Write(new StoryExportModel(
            StoryId: 1, Title: "Migrating Story", AuthorName: "Someone", Rating: Rating.E,
            LongDescriptionHtml: null,
            PublishDate: DateTime.UtcNow, LastUpdatedDate: DateTime.UtcNow,
            Chapters:
            [
                new ChapterExportDto(1, "First Steps", "<p>Opening chapter with <strong>bold</strong> words.</p>", null, null),
                new ChapterExportDto(2, "The Journey", "<p>Second chapter of the migration.</p>", null, null)
            ]));

        await using AsyncServiceScope scope = Factory.Services.CreateAsyncScope();
        IContentImportService import = scope.ServiceProvider.GetRequiredService<IContentImportService>();
        IChapterWriteService write = scope.ServiceProvider.GetRequiredService<IChapterWriteService>();

        ImportParseResult parsed = await import.ParseEpubAsync(new MemoryStream(epub));

        // The author drops the title page in review; commit the two real chapters (the UI loop).
        foreach (ImportedChapterDraft draft in parsed.Drafts.Where(d => d.Title?.StartsWith("Chapter") == true))
        {
            await write.CreateChapterAsync(new CreateChapterDto
            {
                StoryId = storyId,
                Title = draft.Title,
                ChapterText = draft.Html,
                Rating = null
            });
        }

        IReadOnlyList<ChapterListEntryDto> chapters = await write.GetChapterListAsync(storyId);
        chapters.Should().HaveCount(2);
        chapters[0].Title.Should().Be("Chapter 1: First Steps");
        chapters[1].Title.Should().Be("Chapter 2: The Journey");
        chapters.Should().OnlyContain(c => !c.IsPublished,
            "imported chapters are drafts — publish → approval flow is untouched");
        chapters.Should().OnlyContain(c => c.WordCount > 0,
            "word counts are computed server-side from the sanitized import HTML");
    }
}
